CREATE DATABASE TRANSACTION_MANAGEMENT_SYSTEM;

USE  TRANSACTION_MANAGEMENT_SYSTEM;


CREATE TABLE CUSTOMER(
CUSTOMER_ID INT NOT NULL AUTO_INCREMENT,
FIRST_NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL,
CITY VARCHAR(100) NOT NULL,
STATE VARCHAR (100) NOT NULL,
ADDRESS VARCHAR(250) NOT NULL,
CONTACT_NUMBER  VARCHAR(250) NOT NULL UNIQUE,
PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE ACCOUNT(
ACCOUNT_NO VARCHAR(255) NOT NULL PRIMARY KEY,
PIN_CODE INT NOT NULL,
DATE_OF_CREATE DATE NOT NULL ,
ACCOUNT_TYPE VARCHAR(50) NOT NULL,
AMOUNT BIGINT,
CUSTOMER_ID INT NOT NULL,
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE TRANSACTION(
TRX_ID VARCHAR(255) NOT NULL PRIMARY KEY,
DATE_OF_TRANSFER DATETIME NOT NULL, 
AMOUNT BIGINT NOT NULL,
SENDER_ACCOUNT_NUMBER VARCHAR(255) NOT NULL,
RECEIVER_ACCOUNT_NUMBER  VARCHAR(255) NOT NULL,
FOREIGN KEY (SENDER_ACCOUNT_NUMBER) REFERENCES ACCOUNT(ACCOUNT_NO),
FOREIGN KEY (RECEIVER_ACCOUNT_NUMBER) REFERENCES ACCOUNT(ACCOUNT_NO)
);

